"""adding CityState Table

Revision ID: 7dd13f2362e7
Revises: 0317c674f70f
Create Date: 2020-04-20 18:41:10.223280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dd13f2362e7'
down_revision = '0317c674f70f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CityState',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city'),
    sa.UniqueConstraint('state')
    )
    op.create_foreign_key(None, 'Artist', 'CityState', ['city_state'], ['id'])
    op.create_foreign_key(None, 'Venue', 'CityState', ['city_state'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Venue', type_='foreignkey')
    op.drop_constraint(None, 'Artist', type_='foreignkey')
    op.drop_table('CityState')
    # ### end Alembic commands ###
