"""add show table and add missing fields

Revision ID: bc0b8609c211
Revises: 0c2889fe7ae8
Create Date: 2020-04-19 18:32:46.201970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc0b8609c211'
down_revision = '0c2889fe7ae8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Show',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'Artist', sa.Column('seeking_description', sa.String(length=120), nullable=True))
    op.add_column(u'Artist', sa.Column('seeking_venue', sa.Boolean(), nullable=True))
    op.add_column(u'Artist', sa.Column('website', sa.String(length=120), nullable=True))
    op.add_column(u'Venue', sa.Column('seeking_description', sa.String(length=120), nullable=True))
    op.add_column(u'Venue', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.add_column(u'Venue', sa.Column('website', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'Venue', 'website')
    op.drop_column(u'Venue', 'seeking_talent')
    op.drop_column(u'Venue', 'seeking_description')
    op.drop_column(u'Artist', 'website')
    op.drop_column(u'Artist', 'seeking_venue')
    op.drop_column(u'Artist', 'seeking_description')
    op.drop_table('Show')
    # ### end Alembic commands ###
