"""change city_state column name

Revision ID: fb96a477909e
Revises: 7dd13f2362e7
Create Date: 2020-04-20 19:08:37.408196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb96a477909e'
down_revision = '7dd13f2362e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('city_state_id', sa.Integer(), nullable=False))
    op.drop_constraint(u'Artist_city_state_fkey', 'Artist', type_='foreignkey')
    op.create_foreign_key(None, 'Artist', 'CityState', ['city_state_id'], ['id'])
    op.drop_column('Artist', 'city_state')
    op.add_column('Venue', sa.Column('city_state_id', sa.Integer(), nullable=False))
    op.drop_constraint(u'Venue_city_state_fkey', 'Venue', type_='foreignkey')
    op.create_foreign_key(None, 'Venue', 'CityState', ['city_state_id'], ['id'])
    op.drop_column('Venue', 'city_state')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('city_state', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Venue', type_='foreignkey')
    op.create_foreign_key(u'Venue_city_state_fkey', 'Venue', 'CityState', ['city_state'], ['id'])
    op.drop_column('Venue', 'city_state_id')
    op.add_column('Artist', sa.Column('city_state', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Artist', type_='foreignkey')
    op.create_foreign_key(u'Artist_city_state_fkey', 'Artist', 'CityState', ['city_state'], ['id'])
    op.drop_column('Artist', 'city_state_id')
    # ### end Alembic commands ###
